#!/usr/bin/env python3
"""jellyfin-login-methods.py — Cerulean is the identity; Jellyfin's own user store is a last resort.

WHY THIS EXISTS
---------------
Jellyfin cannot join Authentik directly (there is no OIDC support in the server;
its sign-in is a username and a password, whatever backs them). Monarch therefore
gives it two halves, and `docker-compose.yml` documents both:

  * the **gateway** (`jellyfin-sso`, port 14010) demands a Cerulean Authentik
    session before the Jellyfin sign-in page is reachable at all, and
  * the **directory** (`jellyfin-ldap`, the Authentik LDAP outpost) is the
    credential store behind that page, so the account a user types there is their
    Cerulean identity, and disabling them in Authentik locks them out here too.

What that leaves behind is Jellyfin's *own* user database — the thing people mean
by "remove the login auth". Every account Jellyfin holds locally is a second
password, outside Authentik, that no amount of gateway work covers: it can be
generated by a first-run wizard, created by an admin in the UI, or left behind by
a client that self-registers. `jellyfin-admin-password.py` already names the one
local account Monarch *wants* to keep — the break-glass `admin` it keeps in step
with `MONARCH_PASSWORD`, which is how the mobile app and `drift-check` get in.

This script is the other side of that: every local account that is not declared
is reported, and `--apply` disables it.

DECLARED LOCAL ACCOUNTS (`JELLYFIN_LOCAL_ACCOUNTS`)
---------------------------------------------------
The page is published rather than gated (2026-09-18) because the TV and mobile
clients cannot run a browser OIDC flow, and a client that has no LDAP support
signs in against Jellyfin's own store. That is a *deliberate* local account, and
it is indistinguishable from a stray one by inspection: both are a username, a
password Jellyfin owns, and an enabled policy.

So the deployment declares them — `JELLYFIN_LOCAL_ACCOUNTS`, comma-separated, in
`.env` beside `JELLYFIN_ADMIN_USER`. Declared accounts are never reported and
never disabled; drop one from the variable to make it a stray again. The names
live in the operator's `.env` rather than in this repo on purpose: which person
keeps a local login is deployment state, not posture, and a repo that listed it
would go stale the moment that changed. The **count** is printed, so the set
cannot grow silently.

WHY DISABLE RATHER THAN DELETE
------------------------------
Disabling is the reversible end of the same action: Jellyfin refuses the login,
the account's watch history and its identifying id survive, and it can be handed
back to the LDAP directory by enabling it again (at which point the LDAP provider
owns its password). Deleting would look identical from the login page and lose
the history that `magnate-entitlements` and the recommendations read.

WHAT "LOCAL" MEANS, MEASURED
---------------------------
`GET /Users` returns a `UserDto` per account, and the id of the provider that owns
the credential is `AuthenticationProviderId`. The default provider is
`Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider`, which is
the local database; the LDAP plugin's users carry the plugin's id instead. So:

  * an id that is absent or names the default provider -> **local**
  * any other id (the LDAP outpost, a plugin) -> **external**, i.e. Cerulean-owned

JELLYFIN 12 MOVED IT INTO `Policy`, SO BOTH PLACES ARE READ. Measured on this
deployment (12.0.0): the field is no longer a top-level key of the `UserDto` —
the keys are Configuration, EnableAutoLogin, HasConfiguredEasyPassword,
HasConfiguredPassword, HasPassword, Id, LastActivityDate, LastLoginDate, Name,
Policy, ServerId — but `user["Policy"]["AuthenticationProviderId"]` does carry
it, for every account, on `/Users` as well as `/Users/{id}`. Older builds put it
at the top level, so the policy is read first and the account itself second.

Only when neither place reports it is the server's own database asked: the column
still exists in `Users`, and it is the same fact the server acts on, so it is read
from beside the config (`JELLYFIN_DB`, default
`/docker/appdata/jellyfin/data/data/jellyfin.db`) — read-only, matched on
`NormalizedUsername`, and never used for anything but the label.

A build that reports neither cannot be judged, and this says so (exit 2) instead of
passing: "every account is external" and "no account says which provider owns it"
are different facts, and only one of them is good news.

USAGE
-----
    python3 scripts/jellyfin-login-methods.py --check            # report only (default)
    python3 scripts/jellyfin-login-methods.py --apply            # disable the strays
    python3 scripts/jellyfin-login-methods.py --url http://127.0.0.1:8097
    python3 scripts/jellyfin-login-methods.py --db /path/jellyfin.db

Runs on the media host, where Jellyfin's port is published on loopback
(`127.0.0.1:8097`) and the admin API key `monarch-init` exported is at
`/docker/appdata/init/jellyfin-api-key.txt`; `JELLYFIN_API_KEY` overrides it. The
break-glass account is `JELLYFIN_ADMIN_USER` (default `admin`); further local
accounts the deployment keeps are `JELLYFIN_LOCAL_ACCOUNTS` (default empty,
comma-separated).

Header gotcha, inherited from `jellyfin-admin-password.py` and measured there:
this build reads the MediaBrowser header from `Authorization` only —
`X-Emby-Authorization` is rejected with 400, and `X-Emby-Token` / `?api_key=` with
401 even when the credentials are right.

Exit codes: 0 = only declared accounts can sign in locally, 1 = an undeclared
local account was found (or the update failed), 2 = cannot run (no key,
unreachable, or a build that does not report which provider owns an account).
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

DEFAULT_KEY_FILE = Path("/docker/appdata/init/jellyfin-api-key.txt")
DEFAULT_URL = "http://127.0.0.1:8097"
# The server's own database, beside the config it is running from. Consulted only
# when the API omits the owning provider (see the module docstring).
DEFAULT_DB_PATH = Path("/docker/appdata/jellyfin/data/data/jellyfin.db")

# Jellyfin's own credential store. Anything else is a provider the platform owns.
DEFAULT_PROVIDER = "Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider"
DEFAULT_PROVIDER_TAIL = ".DefaultAuthenticationProvider"

CLIENT = ('Client="jellyfin-login-methods", Device="Linux", '
          'DeviceId="monarch-login-methods", Version="1.0"')


class JellyfinError(RuntimeError):
    pass


def api_key(path: Path, override: str) -> str:
    """The key `monarch-init` exported, so nothing has to be pasted in."""
    if override:
        return override
    try:
        key = path.read_text(encoding="utf-8").strip()
    except OSError as error:
        raise JellyfinError(
            f"no Jellyfin API key: {path} is unreadable ({error}) and JELLYFIN_API_KEY is unset"
        ) from None
    if not key:
        raise JellyfinError(f"{path} is empty — has monarch-init run?")
    return key


def call(base_url: str, key: str, method: str, path: str, body: dict | None = None) -> object:
    """One admin call. Returns the parsed body (or None for an empty one)."""
    auth = f'MediaBrowser Token="{key}", {CLIENT}'
    data = json.dumps(body).encode() if body is not None else None
    request = urllib.request.Request(f"{base_url}{path}", data=data, method=method)
    request.add_header("Accept", "application/json")
    request.add_header("Authorization", auth)
    if data is not None:
        request.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(request, timeout=25) as response:
            raw = response.read().decode("utf-8", "replace")
            return json.loads(raw) if raw.strip() else None
    except urllib.error.HTTPError as error:
        detail = (error.read() or b"").decode("utf-8", "replace").strip()[:200]
        # 401 is the key not being accepted; 403 is Jellyfin refusing the change
        # and saying why. They are different problems, and blaming the key for a
        # 403 sent an operator to re-mint a working key — measured, on the
        # `Administrators cannot be disabled.` refusal below.
        if error.code == 401:
            raise JellyfinError(
                f"Jellyfin rejected the admin API key (HTTP 401) — re-mint it with "
                "`python3 scripts/jellyfin-admin-password.py --set`"
            ) from None
        raise JellyfinError(f"{method} {path} answered HTTP {error.code} {detail}".strip()) from None
    except OSError as error:
        raise JellyfinError(f"cannot reach Jellyfin at {base_url} ({error})") from None


# ── classifying the accounts ────────────────────────────────────────────────


def provider_of(user: dict) -> str | None:
    """The provider id Jellyfin reports for this account, or None if it says nothing.

    Jellyfin 12 keeps the field in the account's `Policy` and older builds keep it
    on the account itself, so the policy is asked first and the account second.
    Both spellings are read because the field is serialised camel-cased by the API
    and Pascal-cased in the model, and a Client that returned one of them is not a
    reason to disable the wrong account.
    """
    places = []
    for key in ("Policy", "policy"):
        policy = user.get(key)
        if isinstance(policy, dict):
            places.append(policy)
    places.append(user)

    for place in places:
        for name in ("AuthenticationProviderId", "authenticationProviderId"):
            value = place.get(name)
            if isinstance(value, str) and value.strip():
                return value.strip()
    return None


def is_local(provider: str) -> bool:
    """True when Jellyfin's own database owns the credential."""
    return provider == DEFAULT_PROVIDER or provider.endswith(DEFAULT_PROVIDER_TAIL)


class Account:
    """One Jellyfin account, as far as the two facts that matter are concerned."""

    def __init__(self, user: dict):
        self.id = str(user.get("Id") or user.get("id") or "")
        self.name = str(user.get("Name") or user.get("name") or "")
        self.provider = provider_of(user)
        policy = user.get("Policy") or user.get("policy") or {}
        self.policy = dict(policy) if isinstance(policy, dict) else {}
        self.admin = bool(self.policy.get("IsAdministrator") or self.policy.get("isAdministrator"))
        self.disabled = bool(self.policy.get("IsDisabled") or self.policy.get("isDisabled"))

    @property
    def local(self) -> bool | None:
        """None when this build did not say which provider owns the account."""
        return None if self.provider is None else is_local(self.provider)

    def describe(self) -> str:
        if self.local is None:
            owner = "provider not reported"
        elif self.local:
            owner = "local (Jellyfin's own store)"
        else:
            owner = f"external ({self.provider})"
        flags = []
        if self.admin:
            flags.append("admin")
        if self.disabled:
            flags.append("disabled")
        suffix = f"  [{', '.join(flags)}]" if flags else ""
        return f"  {self.name or '(no name)'}  {owner}{suffix}"


def providers_from_db(path: Path) -> dict[str, str]:
    """`NormalizedUsername -> AuthenticationProviderId`, or {} if unreadable.

    The fallback for a build whose API does not report the field. Opened
    read-only and only ever read: Jellyfin owns this file, and a script that
    writes to a running server's database is a different (and much worse) tool.

    Silent on failure by design — the caller distinguishes "the database says
    nothing" from "there is no database" by the fact that it still cannot judge,
    and a hard error here would make a read-only mount look like a broken
    deployment.
    """
    try:
        connection = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    except sqlite3.Error:
        return {}
    try:
        rows = connection.execute(
            "SELECT NormalizedUsername, Username, AuthenticationProviderId FROM Users"
        ).fetchall()
    except sqlite3.Error:
        return {}
    finally:
        connection.close()

    providers: dict[str, str] = {}
    for normalized, username, provider in rows:
        if not isinstance(provider, str) or not provider.strip():
            continue
        for name in (normalized, username):
            if isinstance(name, str) and name.strip():
                providers[name.strip().lower()] = provider.strip()
    return providers


def fill_from_db(accounts: list[Account], path: Path) -> int:
    """Give every unclassified account the provider the database holds for it.

    Returns how many it could fill, so the caller can tell "the API was silent and
    the database did not know either" from "there was nothing to ask about".
    """
    unknown = [a for a in accounts if a.local is None and a.name]
    if not unknown:
        return 0

    providers = providers_from_db(path)
    if not providers:
        return 0

    filled = 0
    for account in unknown:
        provider = providers.get(account.name.strip().lower())
        if provider:
            account.provider = provider
            filled += 1
    return filled


def declared_local(break_glass: str, extra: str) -> set[str]:
    """The local accounts this deployment keeps on purpose, lower-cased.

    `break_glass` is always one of them; `extra` is JELLYFIN_LOCAL_ACCOUNTS, the
    TV/native-client logins that cannot use the OIDC button. Matched
    case-insensitively because Jellyfin's account names are.
    """
    names = {name.strip().lower() for name in (extra or "").split(",") if name.strip()}
    if break_glass.strip():
        names.add(break_glass.strip().lower())
    return names


def strays(accounts: list[Account], keep: set[str]) -> list[Account]:
    """Local accounts that can still sign in and were not declared.

    A local account that is already disabled is not a way in, so it is reported
    and left alone: it may be a directory user's history waiting to be handed
    back to the LDAP provider.
    """
    return [a for a in accounts if a.local and not a.disabled and a.name.lower() not in keep]


def report(accounts: list[Account], keep: set[str]) -> None:
    declared = sorted(keep)
    print(f"  local accounts declared in the deployment: {len(declared)} "
          f"({', '.join(declared)})")
    for account in accounts:
        print(account.describe())


def disable(base_url: str, key: str, account: Account) -> None:
    """Disable one account, carrying its whole policy back.

    `POST /Users/{id}/Policy` **replaces** the policy rather than merging into
    it, so a body holding only `IsDisabled` would strip the account's library
    access, parental settings and enabled-folders list as a side effect. The
    policy read from `GET /Users` goes back whole, with one field changed.
    """
    policy = dict(account.policy)
    policy["IsDisabled"] = True
    call(base_url, key, "POST", f"/Users/{urllib.parse.quote(account.id)}/Policy", policy)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--apply", action="store_true",
                        help="disable the local accounts (default: report only)")
    parser.add_argument("--check", action="store_true", help="report only, the default")
    parser.add_argument("--url", default=os.environ.get("JELLYFIN_URL", DEFAULT_URL),
                        help=f"Jellyfin base URL (default {DEFAULT_URL})")
    parser.add_argument("--key-file", type=Path,
                        default=Path(os.environ.get("JELLYFIN_KEY_FILE", str(DEFAULT_KEY_FILE))),
                        help=f"the exported admin API key (default {DEFAULT_KEY_FILE})")
    parser.add_argument("--db", type=Path,
                        default=Path(os.environ.get("JELLYFIN_DB", str(DEFAULT_DB_PATH))),
                        help="Jellyfin's own database, read only for the owning provider "
                             f"when the API does not report it (default {DEFAULT_DB_PATH})")
    parser.add_argument("--break-glass",
                        default=os.environ.get("JELLYFIN_ADMIN_USER", "admin"),
                        help="the one local account Monarch keeps (default admin)")
    parser.add_argument("--also-local",
                        default=os.environ.get("JELLYFIN_LOCAL_ACCOUNTS", ""),
                        help="comma-separated further local accounts this deployment "
                             "keeps on purpose (TV/native clients); default empty")
    args = parser.parse_args(argv)

    base_url = args.url.rstrip("/")
    try:
        key = api_key(args.key_file, os.environ.get("JELLYFIN_API_KEY", "").strip())
        users = call(base_url, key, "GET", "/Users")
    except JellyfinError as error:
        print(f"jellyfin-login-methods: {error}", file=sys.stderr)
        return 2

    if not isinstance(users, list):
        print(f"jellyfin-login-methods: GET /Users returned {type(users).__name__}, not a list",
              file=sys.stderr)
        return 2

    accounts = [Account(user) for user in users if isinstance(user, dict)]
    if not accounts:
        print("jellyfin-login-methods: Jellyfin reported no accounts — is this an "
              "administrator key?", file=sys.stderr)
        return 2

    # The API first; the server's own database only for what it left unsaid. On
    # Jellyfin 12 that is every account, because the field is gone from the DTO.
    filled = fill_from_db(accounts, args.db)

    keep = declared_local(args.break_glass, args.also_local)
    print(f"jellyfin-login-methods [{'apply' if args.apply else 'check'}] {base_url}")
    if filled:
        print(f"  provider for {filled} account(s) read from {args.db}")
    report(accounts, keep)

    unknown = [account for account in accounts if account.local is None]
    if unknown:
        print(
            f"\ncannot judge: neither this Jellyfin build's API nor its database "
            f"({args.db}) reports AuthenticationProviderId "
            f"({len(unknown)} of {len(accounts)} account(s)), so 'no local accounts' and "
            "'no account says which provider owns it' cannot be told apart.",
            file=sys.stderr,
        )
        return 2

    offenders = strays(accounts, keep)
    if not offenders:
        print(f"\nok: the only accounts that can sign in locally are the {len(keep)} "
              "this deployment declares.")
        return 0

    print()
    for account in offenders:
        print(f"  local sign-in enabled for {account.name!r}"
              + (" (an administrator)" if account.admin else ""))

    if not args.apply:
        print("\nthose accounts are a credential store outside Authentik — if one is a "
              "client that cannot use the OIDC button, declare it in "
              "JELLYFIN_LOCAL_ACCOUNTS (.env); otherwise re-run with --apply to "
              "disable them.")
        return 1

    failures = 0
    for account in offenders:
        try:
            disable(base_url, key, account)
        except JellyfinError as error:
            failures += 1
            print(f"  could not disable {account.name!r}: {error}", file=sys.stderr)

    # Read it back rather than trusting the write: a policy endpoint that took the
    # request and dropped the field is the failure this whole script exists for.
    try:
        after = [Account(user) for user in call(base_url, key, "GET", "/Users")
                 if isinstance(user, dict)]
    except JellyfinError as error:
        print(f"jellyfin-login-methods: could not re-read the accounts ({error})", file=sys.stderr)
        return 1

    remaining = strays(after, keep)
    for account in remaining:
        print(f"  still enabled: {account.name!r}", file=sys.stderr)

    if failures or remaining:
        return 1

    print(f"\nok: disabled {len(offenders)} local account(s); the {len(keep)} declared "
          "local account(s) are untouched.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
